name = "OscillatorPopulation"
uuid = "fb44ea82-9844-4ac6-9346-0134b9c06618"
authors = ["Vojtech Kumpost <vkumpost@gmail.com>"]
version = "0.1.0"

[deps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"

[extras]
CPUSummary = "2a0fbf3d-bb9c-48f3-b0a9-814d99fd7ab9"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
