authors = ["Vojtech Kumpost <vkumpost@gmail.com>"]
name = "OscillatorPopulation"
uuid = "fb44ea82-9844-4ac6-9346-0134b9c06618"
version = "0.1.0"

[deps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"

[extras]
CPUSummary = "2a0fbf3d-bb9c-48f3-b0a9-814d99fd7ab9"
